/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_cipher1729_ndktest_mainNative */

#ifndef _Included_com_example_cipher1729_ndktest_mainNative
#define _Included_com_example_cipher1729_ndktest_mainNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_cipher1729_ndktest_mainNative
 * Method:    callWithArguments
 * Signature: (Ljava/lang/String;II)I
 */
JNIEXPORT jint JNICALL Java_com_example_cipher1729_ndktest_mainNative_callWithArguments
  (JNIEnv *, jobject, jstring, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
